site_name: Hidl Route
repo_url: https://github.com/HidlRoute/hidlroute-server
copyright: Copyright &copy; 2022 HidlRoute
theme:
  name: material
  logo: assets/images/logo-white-hor-small.svg
  favicon: assets/images/favicon.png
  language: en
  features:
    - navigation.tracking
    - content.tooltips
  # See https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - mike:
      version_selector: true
      css_dir: asstes/styles
      javascript_dir: assets/js
      canonical_version: null       # the version for <link rel="canonical">; `null`
                                    # uses the version specified via `mike deploy`
  - git-revision-date:
      enabled_if_env: CI
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HidlRoute/hidlroute-server
    - icon: fontawesome/solid/paper-plane
      link: mailto:hidlroute-dev@googlegroups.com
  version:
    default: latest
    provider: mike
  analytics:
    provider: google
    property: G-Y6Z53D0FCQ
extra_css:
  - assets/styles/hidlroute.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format